[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install -g pnpm@8", "pnpm install --frozen-lockfile"]
cacheDirectories = ["/root/.local/share/pnpm/store"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm build:cms"]

[start]
cmd = "cd apps/cms && pnpm start"

[variables]
NIXPACKS_NODE_VERSION = "18"