[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm install -g pnpm@8",
    "npx pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
    "npx pnpm db:generate",
    "npx pnpm build:cms"
]

[start]
cmd = "cd apps/cms && npx pnpm start"

[variables]
NIXPACKS_NODE_VERSION = "18"